#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#undef TAPPING_TERM
#define TAPPING_TERM 220

#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT
#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 350
