name: Build Custom QMK Firmware

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

permissions:
  contents: write

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Get changed files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          exclude_submodules: true
          dir_names: true
          dir_names_exclude_current_dir: true
          files: keyboards/**

      - name: Get changed Keyboards
        id: change-summary
        shell: 'bash {0}'
        run: |
          CHANGES=$(echo -e '${{ steps.changed-files.outputs.all_changed_files }}' | sed 's/ /\n/g')
          echo "## Keyboards and Keymaps changed" >> $GITHUB_STEP_SUMMARY
          for file in $CHANGES; do
            KB=$(echo "$file" | sed -e 's/keyboards\///; s/\/keymaps\/\(.*\)$//')
            KM=$(echo "$file" | sed 's/.*\///')
            echo "- $KB / $KM" >> $GITHUB_STEP_SUMMARY
          done
          exit 0

  build:
    name: 'QMK Custom Userspace Build'
    uses: ./.github/workflows/custom_userspace_build.yml
    with:
      qmk_repo: 6ooker/qmk_firmware
      qmk_ref: my_builds
    needs: changed-files

  publish:
    name: 'QMK Custom Userspace Publish'
    uses: ./.github/workflows/custom_userspace_publish.yml
    if: always() && !cancelled()
    with:
      release_body: 
    needs: build